
INCLUDEPATH += displays

FORMS   += displays/dspAllocations.ui \
           displays/dspAPApplications.ui \
           displays/dspAPOpenItemsByVendor.ui \
           displays/dspARApplications.ui \
           displays/dspBOMBase.ui \
           displays/dspBacklogByCustomer.ui \
           displays/dspBacklogByItem.ui \
           displays/dspBacklogByParameterList.ui \
           displays/dspBacklogBySalesOrder.ui \
           displays/dspCapacityUOMsByParameter.ui \
           displays/dspCostedBOMBase.ui \
           displays/dspCostedSummarizedBOM.ui \
           displays/dspCountSlipsByWarehouse.ui \
           displays/dspCountTagsBase.ui \
           displays/dspDepositsRegister.ui \
           displays/dspDetailedInventoryHistoryByLocation.ui \
           displays/dspDetailedInventoryHistoryByLotSerial.ui \
           displays/dspExpiredInventoryByClassCode.ui \
           displays/dspFrozenItemSites.ui \
           displays/dspIndentedWhereUsed.ui \
           displays/dspInventoryAvailabilityByCustomerType.ui \
           displays/dspInventoryAvailabilityByItem.ui \
           displays/dspInventoryAvailabilityByParameterList.ui \
           displays/dspInventoryAvailabilityBySalesOrder.ui \
           displays/dspInventoryAvailabilityBySourceVendor.ui \
           displays/dspInventoryAvailabilityByWorkOrder.ui \
           displays/dspInventoryHistoryBase.ui \
           displays/dspInventoryLocator.ui \
           displays/dspItemCostDetail.ui \
           displays/dspItemCostHistory.ui \
           displays/dspItemCostSummary.ui \
           displays/dspItemCostsByClassCode.ui \
           displays/dspItemsByCharacteristic.ui \
           displays/dspItemsByParameter.ui \
           displays/dspItemSitesByItem.ui \
           displays/dspItemSitesByParameterList.ui \
           displays/dspPendingBOMChanges.ui \
           displays/dspQOHByItem.ui \
           displays/dspQOHByLocation.ui \
           displays/dspQOHByParameterList.ui \
           displays/dspShipmentsBase.ui \
           displays/dspShipmentsByDate.ui \
           displays/dspSingleLevelWhereUsed.ui \
           displays/dspSlowMovingInventoryByClassCode.ui \
           displays/dspSubstituteAvailabilityByItem.ui \
           displays/dspUsageStatisticsBase.ui \
           displays/dspValidLocationsByItem.ui

HEADERS += displays/dspAllocations.h \
           displays/dspAPApplications.h \
           displays/dspAPOpenItemsByVendor.h \
           displays/dspARApplications.h \
           displays/dspBOMBase.h \
           displays/dspBacklogByCustomer.h \
           displays/dspBacklogByItem.h \
           displays/dspBacklogByParameterList.h \
           displays/dspBacklogBySalesOrder.h \
           displays/dspCapacityUOMsByClassCode.h \
           displays/dspCapacityUOMsByParameter.h \
           displays/dspCapacityUOMsByProductCategory.h \
           displays/dspCostedBOMBase.h \
           displays/dspCostedIndentedBOM.h \
           displays/dspCostedSingleLevelBOM.h \
           displays/dspCostedSummarizedBOM.h \
           displays/dspCountSlipsByWarehouse.h \
           displays/dspCountTagsBase.h \
           displays/dspCountTagsByClassCode.h \
           displays/dspCountTagsByItem.h \
           displays/dspCountTagsByWarehouse.h \
           displays/dspDepositsRegister.h \
           displays/dspDetailedInventoryHistoryByLocation.h \
           displays/dspDetailedInventoryHistoryByLotSerial.h \
           displays/dspExpiredInventoryByClassCode.h \
           displays/dspFrozenItemSites.h \
           displays/dspIndentedBOM.h \
           displays/dspIndentedWhereUsed.h \
           displays/dspInventoryAvailabilityByCustomerType.h \
           displays/dspInventoryAvailabilityByItem.h \
           displays/dspInventoryAvailabilityByParameterList.h \
           displays/dspInventoryAvailabilityBySalesOrder.h \
           displays/dspInventoryAvailabilityBySourceVendor.h \
           displays/dspInventoryAvailabilityByWorkOrder.h \
           displays/dspInventoryHistoryBase.h \
           displays/dspInventoryHistoryByItem.h \
           displays/dspInventoryHistoryByOrderNumber.h \
           displays/dspInventoryHistoryByParameterList.h \
           displays/dspInventoryLocator.h \
           displays/dspItemCostDetail.h \
           displays/dspItemCostHistory.h \
           displays/dspItemCostSummary.h \
           displays/dspItemCostsByClassCode.h \
           displays/dspItemsByCharacteristic.h \
           displays/dspItemsByClassCode.h \
           displays/dspItemsByParameter.h \
           displays/dspItemsByProductCategory.h \
           displays/dspItemSitesByItem.h \
           displays/dspItemSitesByParameterList.h \
           displays/dspItemsWithoutItemSources.h \
           displays/dspPendingBOMChanges.h \
           displays/dspQOHByItem.h \
           displays/dspQOHByLocation.h \
           displays/dspQOHByParameterList.h \
           displays/dspShipmentsBase.h \
           displays/dspShipmentsByDate.h \
           displays/dspShipmentsBySalesOrder.h \
           displays/dspShipmentsByShipment.h \
           displays/dspSingleLevelBOM.h \
           displays/dspSingleLevelWhereUsed.h \
           displays/dspSlowMovingInventoryByClassCode.h \
           displays/dspSubstituteAvailabilityByItem.h \
           displays/dspSummarizedBOM.h \
           displays/dspUsageStatisticsBase.h \
           displays/dspUsageStatisticsByClassCode.h \
           displays/dspUsageStatisticsByItem.h \
           displays/dspUsageStatisticsByItemGroup.h \
           displays/dspUsageStatisticsByWarehouse.h \
           displays/dspValidLocationsByItem.h

SOURCES += displays/dspAllocations.cpp \
           displays/dspAPApplications.cpp \
           displays/dspAPOpenItemsByVendor.cpp \
           displays/dspARApplications.cpp \
           displays/dspBOMBase.cpp \
           displays/dspBacklogByCustomer.cpp \
           displays/dspBacklogByItem.cpp \
           displays/dspBacklogByParameterList.cpp \
           displays/dspBacklogBySalesOrder.cpp \
           displays/dspCapacityUOMsByClassCode.cpp \
           displays/dspCapacityUOMsByParameter.cpp \
           displays/dspCapacityUOMsByProductCategory.cpp \
           displays/dspCostedBOMBase.cpp \
           displays/dspCostedIndentedBOM.cpp \
           displays/dspCostedSingleLevelBOM.cpp \
           displays/dspCostedSummarizedBOM.cpp \
           displays/dspCountSlipsByWarehouse.cpp \
           displays/dspCountTagsBase.cpp \
           displays/dspCountTagsByClassCode.cpp \
           displays/dspCountTagsByItem.cpp \
           displays/dspCountTagsByWarehouse.cpp \
           displays/dspDepositsRegister.cpp \
           displays/dspDetailedInventoryHistoryByLocation.cpp \
           displays/dspDetailedInventoryHistoryByLotSerial.cpp \
           displays/dspExpiredInventoryByClassCode.cpp \
           displays/dspFrozenItemSites.cpp \
           displays/dspIndentedBOM.cpp \
           displays/dspIndentedWhereUsed.cpp \
           displays/dspInventoryAvailabilityByCustomerType.cpp \
           displays/dspInventoryAvailabilityByItem.cpp \
           displays/dspInventoryAvailabilityByParameterList.cpp \
           displays/dspInventoryAvailabilityBySalesOrder.cpp \
           displays/dspInventoryAvailabilityBySourceVendor.cpp \
           displays/dspInventoryAvailabilityByWorkOrder.cpp \
           displays/dspInventoryHistoryBase.cpp \
           displays/dspInventoryHistoryByItem.cpp \
           displays/dspInventoryHistoryByOrderNumber.cpp \
           displays/dspInventoryHistoryByParameterList.cpp \
           displays/dspInventoryLocator.cpp \
           displays/dspItemCostDetail.cpp \
           displays/dspItemCostHistory.cpp \
           displays/dspItemCostSummary.cpp \
           displays/dspItemCostsByClassCode.cpp \
           displays/dspItemsByCharacteristic.cpp \
           displays/dspItemsByClassCode.cpp \
           displays/dspItemsByParameter.cpp \
           displays/dspItemsByProductCategory.cpp \
           displays/dspItemSitesByItem.cpp \
           displays/dspItemSitesByParameterList.cpp \
           displays/dspItemsWithoutItemSources.cpp \
           displays/dspPendingBOMChanges.cpp \
           displays/dspQOHByItem.cpp \
           displays/dspQOHByLocation.cpp \
           displays/dspQOHByParameterList.cpp \
           displays/dspShipmentsBase.cpp \
           displays/dspShipmentsByDate.cpp \
           displays/dspShipmentsBySalesOrder.cpp \
           displays/dspShipmentsByShipment.cpp \
           displays/dspSingleLevelBOM.cpp \
           displays/dspSingleLevelWhereUsed.cpp \
           displays/dspSlowMovingInventoryByClassCode.cpp \
           displays/dspSubstituteAvailabilityByItem.cpp \
           displays/dspSummarizedBOM.cpp \
           displays/dspUsageStatisticsBase.cpp \
           displays/dspUsageStatisticsByClassCode.cpp \
           displays/dspUsageStatisticsByItem.cpp \
           displays/dspUsageStatisticsByItemGroup.cpp \
           displays/dspUsageStatisticsByWarehouse.cpp \
           displays/dspValidLocationsByItem.cpp

