#!/bin/bash

if ! [ -d $QTDIR ]; then
  echo "Cannot find QTDIR"
  exit 1
fi
if ! [ -d $PGDIR/lib ]; then
  echo "Cannot find PGDIR/lib"
  exit 1
fi
FRAMEWORKSDIR=../bin/xtuple.app/Contents/Frameworks

if ! [ -d $FRAMEWORKSDIR ] && ! mkdir $FRAMEWORKSDIR    ; then exit 1 ; fi
if ! cd $FRAMEWORKSDIR                                  ; then exit 1 ; fi

LIBRARIES="$QTDIR/lib/libQt3Support.4.dylib
           $QTDIR/lib/libQtAssistantClient.4.dylib
           $QTDIR/lib/libQtNetwork.4.dylib
           $QTDIR/lib/libQtSql.4.dylib
           $QTDIR/lib/libQtXml.4.dylib
           $QTDIR/lib/libQtGui.4.dylib
           $QTDIR/lib/libQtCore.4.dylib
           $PGDIR/lib/libpq.4.dylib"
if ! cp $LIBRARIES .                                    ; then exit 1 ; fi
for TOFIX in $LIBRARIES ; do
  BASETOFIX=`basename $TOFIX`
  install_name_tool -id @executable_path/../Frameworks/$BASETOFIX $BASETOFIX
  for RENAME in $LIBRARIES ; do
    install_name_tool -change $RENAME @executable_path/../Frameworks/`basename $RENAME` $BASETOFIX
    install_name_tool -change $RENAME @executable_path/../Frameworks/`basename $RENAME` ../MacOS/xtuple
  done
done

if ! [ -d "../plugins" ] && ! mkdir ../plugins  ; then exit 2 ; fi
if ! cd ../plugins                              ; then exit 2 ; fi
if ! [ -d "sqldrivers" ] && ! mkdir sqldrivers  ; then exit 2 ; fi
if ! cd sqldrivers                              ; then exit 2 ; fi

cp $QTDIR/plugins/sqldrivers/libqsqlpsql.dylib .
install_name_tool -change $QTDIR/lib/libQtSql.4.dylib @executable_path/../Frameworks/libQtSql.4.dylib libqsqlpsql.dylib
install_name_tool -change $QTDIR/lib/libQtCore.4.dylib @executable_path/../Frameworks/libQtCore.4.dylib libqsqlpsql.dylib
install_name_tool -change $PGDIR/lib/libpq.4.dylib @executable_path/../Frameworks/libpq.4.dylib libqsqlpsql.dylib

cp $QTDIR/plugins/sqldrivers/libqsqlodbc.dylib .
install_name_tool -change $QTDIR/lib/libQtSql.4.dylib @executable_path/../Frameworks/libQtSql.4.dylib libqsqlodbc.dylib
install_name_tool -change $QTDIR/lib/libQtCore.4.dylib @executable_path/../Frameworks/libQtCore.4.dylib libqsqlodbc.dylib

cd ..
if ! [ -d "imageformats" ]; then
  mkdir imageformats
fi
cd imageformats

LIBRARIES="$QTDIR/plugins/imageformats/libqgif.dylib
           $QTDIR/plugins/imageformats/libqjpeg.dylib
           $QTDIR/plugins/imageformats/libqmng.dylib"
if ! cp $LIBRARIES .                            ; then exit 2 ; fi
for TOFIX in $LIBRARIES ; do
  BASETOFIX=`basename $TOFIX`
  for RENAME in $QTDIR/lib/libQtGui.4.dylib \
                $QTDIR/lib/libQtCore.4.dylib ; do
    install_name_tool -change $RENAME @executable_path/../Frameworks/`basename $RENAME` $BASETOFIX
  done
done

if ! cd ../../Resources                         ; then exit 3 ; fi

echo "[Paths]" > qt.conf
echo "Prefix = .." >> qt.conf

if ! cp -r $QTDIR/bin/assistant.app .           ; then exit 3 ; fi
if ! cd assistant.app/Contents/MacOS            ; then exit 3 ; fi
for RENAME in Xml Gui Network Core ; do
  install_name_tool -change $QTDIR/lib/libQt${RENAME}.4.dylib @executable_path/../Frameworks/libQt${RENAME}.4.dylib assistant
done

if ! cd ../Resources                            ; then exit 3 ; fi
# create/copy a qt.conf file pointing to the plugins directory
echo "[Paths]" > qt.conf
echo "Prefix = .." >> qt.conf

if ! cd ..                                      ; then exit 4 ; fi
if [ -L Frameworks ] && ! rm Frameworks         ; then exit 4 ; fi
if ! ln -s ../../../Frameworks                  ; then exit 4 ; fi
if [ -L plugins ] && ! rm plugins               ; then exit 4 ; fi
if ! ln -s ../../../plugins                     ; then exit 4 ; fi

exit 0
