/*
 * This file is part of the xTuple ERP: PostBooks Edition, a free and
 * open source Enterprise Resource Planning software suite,
 * Copyright (c) 1999-2009 by OpenMFG LLC, d/b/a xTuple.
 * It is licensed to you under the Common Public Attribution License
 * version 1.0, the full text of which (including xTuple-specific Exhibits)
 * is available at www.xtuple.com/CPAL.  By using this software, you agree
 * to be bound by its terms.
 */

#include "metasqlHighlighter.h"

#include <QColor>

#include "format.h"

static QStringList _keyword;
static QStringList _extension;

void MetaSQLHighlighter::init()
{
  _commentColor   = namedColor("altemphasis");
  _errorColor     = namedColor("error");
  _extensionColor = namedColor("warning");
  _keywordColor   = namedColor("emphasis");
  _literalColor   = namedColor("future");

  // taken from postgresql docs "SQL Key Words"
  if (_keyword.isEmpty())
    _keyword  << "A"
              << "ABORT"
              << "ABS"
              << "ABSOLUTE"
              << "ACCESS"
              << "ACTION"
              << "ADA"
              << "ADD"
              << "ADMIN"
              << "AFTER"
              << "AGGREGATE"
              << "ALIAS"
              << "ALL"
              << "ALLOCATE"
              << "ALSO"
              << "ALTER"
              << "ALWAYS"
              << "ANALYSE"
              << "ANALYZE"
              << "AND"
              << "ANY"
              << "ARE"
              << "ARRAY"
              << "AS"
              << "ASC"
              << "ASENSITIVE"
              << "ASSERTION"
              << "ASSIGNMENT"
              << "ASYMMETRIC"
              << "AT"
              << "ATOMIC"
              << "ATTRIBUTE"
              << "ATTRIBUTES"
              << "AUTHORIZATION"
              << "AVG"
              << "BACKWARD"
              << "BEFORE"
              << "BEGIN"
              << "BERNOULLI"
              << "BETWEEN"
              << "BIGINT"
              << "BINARY"
              << "BIT"
              << "BITVAR"
              << "BIT_LENGTH"
              << "BLOB"
              << "BOOLEAN"
              << "BOTH"
              << "BREADTH"
              << "BY"
              << "C"
              << "CACHE"
              << "CALL"
              << "CALLED"
              << "CARDINALITY"
              << "CASCADE"
              << "CASCADED"
              << "CASE"
              << "CAST"
              << "CATALOG"
              << "CATALOG_NAME"
              << "CEIL"
              << "CEILING"
              << "CHAIN"
              << "CHAR"
              << "CHARACTER"
              << "CHARACTERISTICS"
              << "CHARACTERS"
              << "CHARACTER_LENGTH"
              << "CHARACTER_SET_CATALOG"
              << "CHARACTER_SET_NAME"
              << "CHARACTER_SET_SCHEMA"
              << "CHAR_LENGTH"
              << "CHECK"
              << "CHECKED"
              << "CHECKPOINT"
              << "CLASS"
              << "CLASS_ORIGIN"
              << "CLOB"
              << "CLOSE"
              << "CLUSTER"
              << "COALESCE"
              << "COBOL"
              << "COLLATE"
              << "COLLATION"
              << "COLLATION_CATALOG"
              << "COLLATION_NAME"
              << "COLLATION_SCHEMA"
              << "COLLECT"
              << "COLUMN"
              << "COLUMN_NAME"
              << "COMMAND_FUNCTION"
              << "COMMAND_FUNCTION_CODE"
              << "COMMENT"
              << "COMMIT"
              << "COMMITTED"
              << "COMPLETION"
              << "CONCURRENTLY"
              << "CONDITION"
              << "CONDITION_NUMBER"
              << "CONNECT"
              << "CONNECTION"
              << "CONNECTION_NAME"
              << "CONSTRAINT"
              << "CONSTRAINTS"
              << "CONSTRAINT_CATALOG"
              << "CONSTRAINT_NAME"
              << "CONSTRAINT_SCHEMA"
              << "CONSTRUCTOR"
              << "CONTAINS"
              << "CONTINUE"
              << "CONVERSION"
              << "CONVERT"
              << "COPY"
              << "CORR"
              << "CORRESPONDING"
              << "COUNT"
              << "COVAR_POP"
              << "COVAR_SAMP"
              << "CREATE"
              << "CREATEDB"
              << "CREATEROLE"
              << "CREATEUSER"
              << "CROSS"
              << "CSV"
              << "CUBE"
              << "CUME_DIST"
              << "CURRENT"
              << "CURRENT_DATE"
              << "CURRENT_DEFAULT_TRANSFORM_GROUP"
              << "CURRENT_PATH"
              << "CURRENT_ROLE"
              << "CURRENT_TIME"
              << "CURRENT_TIMESTAMP"
              << "CURRENT_TRANSFORM_GROUP_FOR_TYPE"
              << "CURRENT_USER"
              << "CURSOR"
              << "CURSOR_NAME"
              << "CYCLE"
              << "DATA"
              << "DATABASE"
              << "DATE"
              << "DATETIME_INTERVAL_CODE"
              << "DATETIME_INTERVAL_PRECISION"
              << "DAY"
              << "DEALLOCATE"
              << "DEC"
              << "DECIMAL"
              << "DECLARE"
              << "DEFAULT"
              << "DEFAULTS"
              << "DEFERRABLE"
              << "DEFERRED"
              << "DEFINED"
              << "DEFINER"
              << "DEGREE"
              << "DELETE"
              << "DELIMITER"
              << "DELIMITERS"
              << "DENSE_RANK"
              << "DEPTH"
              << "DEREF"
              << "DERIVED"
              << "DESC"
              << "DESCRIBE"
              << "DESCRIPTOR"
              << "DESTROY"
              << "DESTRUCTOR"
              << "DETERMINISTIC"
              << "DIAGNOSTICS"
              << "DICTIONARY"
              << "DISABLE"
              << "DISCONNECT"
              << "DISPATCH"
              << "DISTINCT"
              << "DO"
              << "DOMAIN"
              << "DOUBLE"
              << "DROP"
              << "DYNAMIC"
              << "DYNAMIC_FUNCTION"
              << "DYNAMIC_FUNCTION_CODE"
              << "EACH"
              << "ELEMENT"
              << "ELSE"
              << "ENABLE"
              << "ENCODING"
              << "ENCRYPTED"
              << "END"
              << "END-EXEC"
              << "EQUALS"
              << "ESCAPE"
              << "EVERY"
              << "EXCEPT"
              << "EXCEPTION"
              << "EXCLUDE"
              << "EXCLUDING"
              << "EXCLUSIVE"
              << "EXEC"
              << "EXECUTE"
              << "EXISTING"
              << "EXISTS"
              << "EXP"
              << "EXPLAIN"
              << "EXTERNAL"
              << "EXTRACT"
              << "FALSE"
              << "FETCH"
              << "FILTER"
              << "FINAL"
              << "FIRST"
              << "FLOAT"
              << "FLOOR"
              << "FOLLOWING"
              << "FOR"
              << "FORCE"
              << "FOREIGN"
              << "FORTRAN"
              << "FORWARD"
              << "FOUND"
              << "FREE"
              << "FREEZE"
              << "FROM"
              << "FULL"
              << "FUNCTION"
              << "FUSION"
              << "G"
              << "GENERAL"
              << "GENERATED"
              << "GET"
              << "GLOBAL"
              << "GO"
              << "GOTO"
              << "GRANT"
              << "GRANTED"
              << "GREATEST"
              << "GROUP"
              << "GROUPING"
              << "HANDLER"
              << "HAVING"
              << "HEADER"
              << "HIERARCHY"
              << "HOLD"
              << "HOST"
              << "HOUR"
              << "IDENTITY"
              << "IF"
              << "IGNORE"
              << "ILIKE"
              << "IMMEDIATE"
              << "IMMUTABLE"
              << "IMPLEMENTATION"
              << "IMPLICIT"
              << "IN"
              << "INCLUDING"
              << "INCREMENT"
              << "INDEX"
              << "INDEXES"
              << "INDICATOR"
              << "INFIX"
              << "INHERIT"
              << "INHERITS"
              << "INITIALIZE"
              << "INITIALLY"
              << "INNER"
              << "INOUT"
              << "INPUT"
              << "INSENSITIVE"
              << "INSERT"
              << "INSTANCE"
              << "INSTANTIABLE"
              << "INSTEAD"
              << "INT"
              << "INTEGER"
              << "INTERSECT"
              << "INTERSECTION"
              << "INTERVAL"
              << "INTO"
              << "INVOKER"
              << "IS"
              << "ISNULL"
              << "ISOLATION"
              << "ITERATE"
              << "JOIN"
              << "K"
              << "KEY"
              << "KEY_MEMBER"
              << "KEY_TYPE"
              << "LANCOMPILER"
              << "LANGUAGE"
              << "LARGE"
              << "LAST"
              << "LATERAL"
              << "LEADING"
              << "LEAST"
              << "LEFT"
              << "LENGTH"
              << "LESS"
              << "LEVEL"
              << "LIKE"
              << "LIMIT"
              << "LISTEN"
              << "LN"
              << "LOAD"
              << "LOCAL"
              << "LOCALTIME"
              << "LOCALTIMESTAMP"
              << "LOCATION"
              << "LOCATOR"
              << "LOCK"
              << "LOGIN"
              << "LOWER"
              << "M"
              << "MAP"
              << "MATCH"
              << "MATCHED"
              << "MAX"
              << "MAXVALUE"
              << "MEMBER"
              << "MERGE"
              << "MESSAGE_LENGTH"
              << "MESSAGE_OCTET_LENGTH"
              << "MESSAGE_TEXT"
              << "METHOD"
              << "MIN"
              << "MINUTE"
              << "MINVALUE"
              << "MOD"
              << "MODE"
              << "MODIFIES"
              << "MODIFY"
              << "MODULE"
              << "MONTH"
              << "MORE"
              << "MOVE"
              << "MULTISET"
              << "MUMPS"
              << "NAME"
              << "NAMES"
              << "NATIONAL"
              << "NATURAL"
              << "NCHAR"
              << "NCLOB"
              << "NESTING"
              << "NEW"
              << "NEXT"
              << "NO"
              << "NOCREATEDB"
              << "NOCREATEROLE"
              << "NOCREATEUSER"
              << "NOINHERIT"
              << "NOLOGIN"
              << "NONE"
              << "NORMALIZE"
              << "NORMALIZED"
              << "NOSUPERUSER"
              << "NOT"
              << "NOTHING"
              << "NOTIFY"
              << "NOTNULL"
              << "NOWAIT"
              << "NULL"
              << "NULLABLE"
              << "NULLIF"
              << "NULLS"
              << "NUMBER"
              << "NUMERIC"
              << "OBJECT"
              << "OCTETS"
              << "OCTET_LENGTH"
              << "OF"
              << "OFF"
              << "OFFSET"
              << "OIDS"
              << "OLD"
              << "ON"
              << "ONLY"
              << "OPEN"
              << "OPERATION"
              << "OPERATOR"
              << "OPTION"
              << "OPTIONS"
              << "OR"
              << "ORDER"
              << "ORDERING"
              << "ORDINALITY"
              << "OTHERS"
              << "OUT"
              << "OUTER"
              << "OUTPUT"
              << "OVER"
              << "OVERLAPS"
              << "OVERLAY"
              << "OVERRIDING"
              << "OWNED"
              << "OWNER"
              << "PAD"
              << "PARAMETER"
              << "PARAMETERS"
              << "PARAMETER_MODE"
              << "PARAMETER_NAME"
              << "PARAMETER_ORDINAL_POSITION"
              << "PARAMETER_SPECIFIC_CATALOG"
              << "PARAMETER_SPECIFIC_NAME"
              << "PARAMETER_SPECIFIC_SCHEMA"
              << "PARTIAL"
              << "PARTITION"
              << "PASCAL"
              << "PASSWORD"
              << "PATH"
              << "PERCENTILE_CONT"
              << "PERCENTILE_DISC"
              << "PERCENT_RANK"
              << "PLACING"
              << "PLI"
              << "POSITION"
              << "POSTFIX"
              << "POWER"
              << "PRECEDING"
              << "PRECISION"
              << "PREFIX"
              << "PREORDER"
              << "PREPARE"
              << "PREPARED"
              << "PRESERVE"
              << "PRIMARY"
              << "PRIOR"
              << "PRIVILEGES"
              << "PROCEDURAL"
              << "PROCEDURE"
              << "PUBLIC"
              << "QUOTE"
              << "RANGE"
              << "RANK"
              << "READ"
              << "READS"
              << "REAL"
              << "REASSIGN"
              << "RECHECK"
              << "RECURSIVE"
              << "REF"
              << "REFERENCES"
              << "REFERENCING"
              << "REGR_AVGX"
              << "REGR_AVGY"
              << "REGR_COUNT"
              << "REGR_INTERCEPT"
              << "REGR_R2"
              << "REGR_SLOPE"
              << "REGR_SXX"
              << "REGR_SXY"
              << "REGR_SYY"
              << "REINDEX"
              << "RELATIVE"
              << "RELEASE"
              << "RENAME"
              << "REPEATABLE"
              << "REPLACE"
              << "RESET"
              << "RESTART"
              << "RESTRICT"
              << "RESULT"
              << "RETURN"
              << "RETURNED_CARDINALITY"
              << "RETURNED_LENGTH"
              << "RETURNED_OCTET_LENGTH"
              << "RETURNED_SQLSTATE"
              << "RETURNING"
              << "RETURNS"
              << "REVOKE"
              << "RIGHT"
              << "ROLE"
              << "ROLLBACK"
              << "ROLLUP"
              << "ROUTINE"
              << "ROUTINE_CATALOG"
              << "ROUTINE_NAME"
              << "ROUTINE_SCHEMA"
              << "ROW"
              << "ROWS"
              << "ROW_COUNT"
              << "ROW_NUMBER"
              << "RULE"
              << "SAVEPOINT"
              << "SCALE"
              << "SCHEMA"
              << "SCHEMA_NAME"
              << "SCOPE"
              << "SCOPE_CATALOG"
              << "SCOPE_NAME"
              << "SCOPE_SCHEMA"
              << "SCROLL"
              << "SEARCH"
              << "SECOND"
              << "SECTION"
              << "SECURITY"
              << "SELECT"
              << "SELF"
              << "SENSITIVE"
              << "SEQUENCE"
              << "SERIALIZABLE"
              << "SERVER_NAME"
              << "SESSION"
              << "SESSION_USER"
              << "SET"
              << "SETOF"
              << "SETS"
              << "SHARE"
              << "SHOW"
              << "SIMILAR"
              << "SIMPLE"
              << "SIZE"
              << "SMALLINT"
              << "SOME"
              << "SOURCE"
              << "SPACE"
              << "SPECIFIC"
              << "SPECIFICTYPE"
              << "SPECIFIC_NAME"
              << "SQL"
              << "SQLCODE"
              << "SQLERROR"
              << "SQLEXCEPTION"
              << "SQLSTATE"
              << "SQLWARNING"
              << "SQRT"
              << "STABLE"
              << "START"
              << "STATE"
              << "STATEMENT"
              << "STATIC"
              << "STATISTICS"
              << "STDDEV_POP"
              << "STDDEV_SAMP"
              << "STDIN"
              << "STDOUT"
              << "STORAGE"
              << "STRICT"
              << "STRUCTURE"
              << "STYLE"
              << "SUBCLASS_ORIGIN"
              << "SUBLIST"
              << "SUBMULTISET"
              << "SUBSTRING"
              << "SUM"
              << "SUPERUSER"
              << "SYMMETRIC"
              << "SYSID"
              << "SYSTEM"
              << "SYSTEM_USER"
              << "TABLE"
              << "TABLESAMPLE"
              << "TABLESPACE"
              << "TABLE_NAME"
              << "TEMP"
              << "TEMPLATE"
              << "TEMPORARY"
              << "TERMINATE"
              << "THAN"
              << "THEN"
              << "TIES"
              << "TIME"
              << "TIMESTAMP"
              << "TIMEZONE_HOUR"
              << "TIMEZONE_MINUTE"
              << "TO"
              << "TOP_LEVEL_COUNT"
              << "TRAILING"
              << "TRANSACTION"
              << "TRANSACTIONS_COMMITTED"
              << "TRANSACTIONS_ROLLED_BACK"
              << "TRANSACTION_ACTIVE"
              << "TRANSFORM"
              << "TRANSFORMS"
              << "TRANSLATE"
              << "TRANSLATION"
              << "TREAT"
              << "TRIGGER"
              << "TRIGGER_CATALOG"
              << "TRIGGER_NAME"
              << "TRIGGER_SCHEMA"
              << "TRIM"
              << "TRUE"
              << "TRUNCATE"
              << "TRUSTED"
              << "TYPE"
              << "UESCAPE"
              << "UNBOUNDED"
              << "UNCOMMITTED"
              << "UNDER"
              << "UNENCRYPTED"
              << "UNION"
              << "UNIQUE"
              << "UNKNOWN"
              << "UNLISTEN"
              << "UNNAMED"
              << "UNNEST"
              << "UNTIL"
              << "UPDATE"
              << "UPPER"
              << "USAGE"
              << "USER"
              << "USER_DEFINED_TYPE_CATALOG"
              << "USER_DEFINED_TYPE_CODE"
              << "USER_DEFINED_TYPE_NAME"
              << "USER_DEFINED_TYPE_SCHEMA"
              << "USING"
              << "VACUUM"
              << "VALID"
              << "VALIDATOR"
              << "VALUE"
              << "VALUES"
              << "VARCHAR"
              << "VARIABLE"
              << "VARYING"
              << "VAR_POP"
              << "VAR_SAMP"
              << "VERBOSE"
              << "VIEW"
              << "VOLATILE"
              << "WHEN"
              << "WHENEVER"
              << "WHERE"
              << "WIDTH_BUCKET"
              << "WINDOW"
              << "WITH"
              << "WITHIN"
              << "WITHOUT"
              << "WORK"
              << "WRITE"
              << "YEAR"
              << "ZONE"
              ;

  // these are metasql key words from http://www.xtuple.org/node/270
  if (_extension.isEmpty())
    _extension  << "break"
                << "continue"
                << "else"
                << "elseif"
                << "endforeach"
                << "endif"
                << "exists"
                << "foreach"
                << "if"
                << "isFirst"
                << "isLast"
                << "literal"
                << "not"
                << "reExists"
                << "value"
                ;

  _kwtest.setPattern("^(" + _keyword.join("|") + ")((?=\\W)|$)");
  _kwtest.setCaseSensitivity(Qt::CaseInsensitive);

  _extest.setPattern("^(" + _extension.join("|") + ")((?=\\W)|$)");
  _numerictest.setPattern("^(0[xX][0-9a-fA-F]+)|(-?[0-9]+(\\.[0-9]+)?)");
  _wordtest.setPattern("^\\w+");
  _quotetest.setPattern("^\"[^\"]*\"|'[^']*'");
}

MetaSQLHighlighter::MetaSQLHighlighter(QObject *parent)
  : QSyntaxHighlighter(parent)
{
  init();
}

MetaSQLHighlighter::MetaSQLHighlighter(QTextDocument *document)
  : QSyntaxHighlighter(document)
{
  init();
}

MetaSQLHighlighter::MetaSQLHighlighter(QTextEdit *editor)
  : QSyntaxHighlighter(editor)
{
  init();
}

MetaSQLHighlighter::~MetaSQLHighlighter()
{
}

void MetaSQLHighlighter::highlightBlock(const QString &text)
{
  int state = previousBlockState();
  int start = 0;

  for (int i = 0; i < text.length(); i++)
  {
    if (state == InsideString)
    {
      // TODO: if i == 0 then error color until next "
      if (text.mid(i, 1) == "\"")
      {
        state = NormalState;
        setFormat(start, i - start + 1, _literalColor);
        start = i;
      }
    }
    else if (text.mid(i, 2) == "--")
    {
      setFormat(i, text.length() - i, _commentColor);
      break;
    }
    else if (_quotetest.indexIn(text.mid(i)) == 0)
    {
      setFormat(i, _quotetest.matchedLength(), _literalColor);
      i += _quotetest.matchedLength();
    }
    else if (text.mid(i, 2) == "''")
    {
      start = i;
      state = InsideString;
    }
    else if (_kwtest.indexIn(text.mid(i)) == 0)
    {
      setFormat(i, _kwtest.matchedLength(), _keywordColor);
      i += _kwtest.matchedLength();
    }
    else if (_extest.indexIn(text.mid(i)) == 0)
    {
      setFormat(i, _extest.matchedLength(), _extensionColor);
      i += _extest.matchedLength();
    }
    else if (_numerictest.indexIn(text.mid(i)) == 0)
    {
      setFormat(i, _numerictest.matchedLength(), _literalColor);
      i += _numerictest.matchedLength();
    }
    else if (_wordtest.indexIn(text.mid(i)) == 0)        // skip non-keywords
      i += _wordtest.matchedLength();
  }

  if (state == InsideString)
    setFormat(start, text.length() - start, _errorColor);

  setCurrentBlockState(state);
}
